---
abstract: 'Find The Longest Common Substring of Two Strings.'
author:
  - 'M. Riester <limaone@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.07
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-LCSS_XS
provides:
  String::LCSS_XS:
    file: lib/String/LCSS_XS.pm
    version: 1.3
requires:
  Exporter: 0
  XSLoader: 0
  perl: v5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/lima1/p5-string-lcss_xs
version: 1.3
